# Generated by Django 4.1.3 on 2022-11-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("from_time", models.TimeField()),
                ("to_time", models.TimeField()),
                ("date", models.DateField()),
            ],
        ),
    ]
